---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Social:
  - Lemmy:
    - abbr: LE
      href: https://lemmy.world/
      icon: lemmy.png

- Galactica:
  - Homepage:
    - abbr: HP
      href: {{HOMEPAGE_FILE_GALACTICA_URL}}
      icon: si-homeassistant
